# Generated by Django 5.0.7 on 2024-07-31 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_code", models.CharField(max_length=20, unique=True)),
                ("department_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_code", models.CharField(max_length=20, unique=True)),
                ("faculty_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "faculty",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_code", models.CharField(max_length=20, unique=True)),
                ("session_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Disabled"), ("1", "Active")], max_length=1
                    ),
                ),
            ],
            options={
                "db_table": "session",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Lecturer", "Lecturer"),
                            ("Exam_Officer", "Exam Officer"),
                            ("HOD", "Head of Department"),
                            ("Student", "Student"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "user_role",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("credit_unit", models.IntegerField(default=0)),
                (
                    "semester",
                    models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1),
                ),
                ("level", models.CharField(max_length=20)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("Elective", "Elective"),
                            ("Prerequisite", "Prerequisite"),
                            ("Normal", "Normal"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Disabled"), ("1", "Active")],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ResultSystem.faculty"
            ),
        ),
        migrations.CreateModel(
            name="GeneralEssayQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("assigned_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("level", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
            ],
            options={
                "db_table": "general_questions",
            },
        ),
        migrations.CreateModel(
            name="GeneralEssayAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_answer", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.generalessayquestions",
                    ),
                ),
            ],
            options={
                "db_table": "general_essay_answer",
            },
        ),
        migrations.CreateModel(
            name="ObjectivesQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("question", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                ("assigned_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
            ],
            options={
                "db_table": "objective_questions",
            },
        ),
        migrations.CreateModel(
            name="ObjectivesAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct_option", models.CharField(max_length=1)),
                ("answer", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.objectivesquestions",
                    ),
                ),
            ],
            options={
                "db_table": "objective_answers",
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prog_name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Disabled"), ("1", "Active")], max_length=1
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
            ],
            options={
                "db_table": "programme",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=45, unique=True)),
                ("surname", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.AddField(
            model_name="objectivesquestions",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ResultSystem.staff"
            ),
        ),
        migrations.AddField(
            model_name="generalessayquestions",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ResultSystem.staff"
            ),
        ),
        migrations.CreateModel(
            name="CourseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.session",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.staff",
                    ),
                ),
            ],
            options={
                "db_table": "course_allocation",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("surname", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Disabled"), ("1", "Active")], max_length=1
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.faculty",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.programme",
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="SemesterCourseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1),
                ),
                ("level", models.CharField(max_length=20)),
                ("practicals", models.DecimalField(decimal_places=2, max_digits=5)),
                ("test_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("exam_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=2)),
                ("grade_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "credit_unit_grade_point",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("credit_earned", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_results",
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1),
                ),
                ("level", models.CharField(max_length=20)),
                ("tcr", models.IntegerField(default=0)),
                ("tce", models.IntegerField(default=0)),
                ("total_credit_grade_points", models.IntegerField(default=0)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cgpa", models.DecimalField(decimal_places=2, max_digits=5)),
                ("carry_over", models.CharField(max_length=100)),
                ("remarks", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.student",
                    ),
                ),
            ],
            options={
                "db_table": "results",
            },
        ),
        migrations.CreateModel(
            name="CourseEnrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_enrolled", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_enrolment",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1),
                ),
                ("date", models.DateField()),
                ("attended", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
            },
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_credit_registered", models.IntegerField(default=0)),
                ("total_credit_earned", models.IntegerField(default=0)),
                ("total_credit_required", models.IntegerField(default=72)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_progress",
            },
        ),
        migrations.CreateModel(
            name="SubjectiveQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("question", models.TextField()),
                ("assigned_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.staff",
                    ),
                ),
            ],
            options={
                "db_table": "subjective_questions",
            },
        ),
        migrations.CreateModel(
            name="SubjectiveAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_answer", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.subjectivequestions",
                    ),
                ),
            ],
            options={
                "db_table": "subjective_answer",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("assigned_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.department",
                    ),
                ),
                (
                    "essay_questions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.generalessayquestions",
                    ),
                ),
                (
                    "objectives",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.objectivesquestions",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.staff",
                    ),
                ),
                (
                    "subjectives",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResultSystem.subjectivequestions",
                    ),
                ),
            ],
            options={
                "db_table": "exam",
            },
        ),
    ]
